services:
  db:
    image: mysql:8.0
    restart: always
    shm_size: 128mb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - './mysql_data:/var/lib/mysql'
    ports:
      - "3306:3306"
  app:
    build:
      context: .
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXP: ${JWT_EXP}
      DATABASE_URL: "mysql://root:PalomaH1@localhost:3306/prismaequipo"
    depends_on:
      - localhost
    ports:
      - 3000:3000